### ISSUE TITLE
UAT Case 1 - Logged in user initiates request access to one or more restricted files in single dataset

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#43]
Pre-condition: user with regular permissions (ie. not ADA admin) in Dataverse has logged in

Steps:

1. [Dataverse] User navigates to a dataset for which there is at least 1 restricted file that they can 'Request Access' to
2. User clicks the 'button' to the right of the file
3. In the drop-down list, the user selects 'Request Access'
4. A Dataverse popup with the dataset Terms and Conditions is presented to the user
5. The user clicks 'Accept'
6. The requestaccess tool (requestaccess-test.ada.edu.au during testing, requestaccess.ada.edu.au in production) is opened in a new tab in the user's browser

**Comment by HaddicanGitHub** [comment]
The following actions were completed during testing of Use Case 1. 
1. Logged on to DV5 at https://dataverse5-test.ada.edu.au/dataverse/ada using Test Account
2. Navigated to ANU Poll 47 at https://dataverse5-test.ada.edu.au/dataset.xhtml?persistentId=doi:10.26193/YB3CXX
3. Selected the Download Icon to the right of a restricted access file, which opened up drop-down list
4. Selected 'Request Access'
5. Presented with dataset 'T&Cs' page
6 Clicked 'Accept'
7. Presented with 'Email Unconfirmed' message as my test email was deliberately unverified for this activity. 
Good intervention - this will help to prevent unverified users from applying for data. Could we perhaps add a link to the email unconfirmed message page that directs the user back to their Dataverse Homepage so that users can click on this? And/or provide instructions regarding how to verify their account - I can provide wording if required. 

**Edit MM: The how to verify email details have been added see issue #72.**

8. Email verified
9. Navigated back to ANU Poll 47 data
10. Selected the Download Icon to the right of a restricted access file, which opened up drop-down list
11. Selected 'Request Access'
12. Presented with dataset 'T&Cs' page
13. Clicked 'Accept'
14. Request Access 'online Guestbook' presented in new tab

No issues experienced with the above. Test was concluded by saving my application using the 'Save' button. I also received an email with my saved answers and a link to re-open the application. I am assuming I will test this functionality in one of the other tests.

**Comment by HeatherLeasor** [comment]
1 logged into dv5 using Heather-test
2 Lowy 19
3 request
4 acpet tc
5 click all in request access no sibling dv show
6 accept tc tu
7 see requests submitted
8 recieved email in my gmail
9 recieve email in osticket 338016
10 click link in os ticket and granted self
11 reiceved email granted access in gmail
12 clicked remove access and removed all 5 files 
13 no email sent about removal from dv **(MM: check if this is a bug in core dataverse code)**

**Comment by HeatherLeasor** [comment]
zaza did without verified hotmail and got a block to verify before could proceed even for open data document.
when clicking on documents acknowledgement of HILDA GR 19 which should be an open document.
Bug?

**Edited by Marina 08022022 15:25:**
When checkboxes to the left of the open files are selected and then the multi-select 'Download' button is clicked, the files are downloaded (as expected - no bug).

When checkboxes to the left of the open files are selected and then the multi-select 'Request Access' button is clicked, the request access application tool is opened.
I checked this behaviour on archive-vanilla.ada.edu.au (core Dataverse code, not my Dataverse fork with the external access request tool). The multi-select 'Request Access' button is always enabled so the user can always click it.

So on archive-vanilla, the user can select all unrestricted files and then click multi-select Request Access. No access requests are actually 'made' by this action in the core Dataverse code but in my dataverse fork on dataverse5-test.ada.edu.au, clicking that multi-select Request Access button automatically launches the request access tool because  it assumes clicking that 'Request Access' button is valid (there are restricted files being requested).
 
So the bug in the core dataverse code (having the multi-select Request Access button always enabled even when there are no restricted files in the multi-file select) is resulting in a bug in my fork.

**Comment by HeatherLeasor** [comment]
HILDa 19 GR the documentation requires filling out guestbook and being logged in. when it should be a clear download.

**Edited by Marina 08022022 15:50:**
The documentation is downloading fine using the multi-file 'Download' button.
It's not supposed to download when the user clicks multi-file 'Request Access' button. (The request access tool opening is not wanted either but I will have to look at that as per my comment above).
