### ISSUE TITLE
UAT Case 7 - ADA access manager grants/rejects access to a user based on a submitted access request

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#51]
Pre-requisites:
A user has requested access through the requestaccess tool.
A ticket has been created for that request access.

Steps.
1. Access manager accesses the ticket in osticket and deems the access request worthy/unworthy
2. Access manager clicks the 'Manage permissions' link to go to the dataset
3. In the dataset, access manager goes to Edit->Permissions->File
4. In the 'Requests' Section, the access manager finds the user
5. The access manager clicks Grant (request worthy) or Reject (request unworthy) 

Expected results:
1. Grant/Worthy
a. the user is granted FileDownloader role in the roleassignement table
b. the rows for the user/fileid are deleted from the fileaccessrequests table
c. in the ADA access manager's Dataverse UI, the user moves from the 'Requests' section of the Edit->Permissions->File UI to the ' ' section below to indicate they now have access
d. the requester receives an email saying they have been granted access
e. in the Dataverse ui for the requester, the files' dropdown links that the user has been granted access to now show 'Download'
f. The user can download the file(s)

2. Reject/Unworthy
a. the rows for the user/fileid are deleted from the fileaccessrequests table
b. in the ADA access manager's Dataverse UI, the user is removed from the 'Requests' section of the Edit->Permissions->File UI 
c. the requester receives a notification saying their request has been rejected
d. in the Dataverse UI for the requester, the files' dropdown links once again show 'Request Access' which means the user can request the same files again

**Comment by HaddicanGitHub** [comment]
Using the original request for access to ANU Poll 47 via my personal account, I located the ticket in OSTicket #701708 at https://support.ada.edu.au/scp/tickets.php?id=29272#note

Note - no email was sent to ADA email address notifying the User Services team that a request had been received. I had to find the ticket manually in OSTicket. **Edit MM: this has now been fixed in issue #71** 

When I select the Manage permissions link in the OSTicket at https://dataverse5-test.ada.edu.au/permissions-manage-files.xhtml?id=17410, there is no request in the system for the user. I suspect this is because DV thinks that the user has not submitted the application, because it sees the re-open access link as being used, even though it hasn't been used. 
**Edit MM: there was an issue with the way the re-open form link was being copied and pasted - if the right-click menu item then paste was used, somehow (not sure how) the link was being 'used' even though nothing appeared to have been activated by it.**

I have navigated back to the same dataset as a user, and request access is visible again. This does suggest that the original request is no longer open.

**Comment by HaddicanGitHub** [comment]
Interestingly, when I go back in to raise a new request using the same dataset as before (ANU Poll 47), 'Request Access' is visible to me again and my original answers are all pre-populated in the guestbook. 

So it is as if the re-open link has worked, because the answers are there. But the error message suggests that the link had already been used prior to me selecting it on the first attempt. 

Also, 'Request Access' is available again in the drop-down menu, should this be the case if the ticket was effectively sent back to the user to edit?

**Comment by HaddicanGitHub** [comment]
Reject Access Test
1. ﻿New application raised at Ticket #419717 https://support.ada.edu.au/scp/tickets.php?id=29281
2. Access request now appears in DV 5 as an actual request unlike with the test above when the access request did not appear using the re-open function.
﻿3. Access Rejected by User Services Officer on this occasion for testing purposes as per option 2 of testing above. 
﻿4. The Users details are not automatically removed from the Users/Groups list in the access page on Dataverse. I had to refresh the page to get the list to update which is not required with the current version of DV. Screenshot below shows the view after Reject has been selected but screen not refreshed. 
5. ﻿Email received by user confirming rejection, user also has message in DV Notifications that access was rejected. 
6. User can again see the 'Request Access' option for the data file.

![Access Screen after selecting Reject](https://user-images.githubusercontent.com/78828143/152713976-96614e52-a571-480e-a13c-937c91a0497a.PNG)

**Comment by HaddicanGitHub** [comment]
Approved Access Test:
1. New application raised at Ticket #224379 https://support.ada.edu.au/scp/tickets.php?id=29285#reply
2. Access request appears in DV 5 when User Services Officer navigates to ticket.
3. Access granted to user by User Services Officer. As per Reject Test, the details are not automatically removed from the Request field and populated in the Approved access field. I had to refresh the screen to effect these changes.  
**Edit MM: This issue is a Dataverse issue, not a request access tool issue.**
4. Email received by user confirming that access has been approved. 
5. User is able to access data using link in email, and download data file.

**Comment by HaddicanGitHub** [comment]
Forced Approved Access Test:
When an application has been erroneously closed and ADA staff need to update permissions without getting user to re-submit access request, or where email request is sufficient (i.e. for HILDA 16 in ACSPRI Courses).

1. Logged in as ADA User Services
2. Navigated to ANU Poll 35 at https://dataverse5-test.ada.edu.au/dataset.xhtml?persistentId=doi:10.26193/ZFGFNE
3. Selected Edit Dataset - Permissions - File
4. Selected Grant Access to Users/Groups
5. Entered Users Username into user field and approved access
6. Table Automatically Updated with user details in this instance (unlike above using 'Grant/Reject' buttons)
7. Email received by User confirming access has been granted
8. Notification in Dataverse received by user confirming access has been granted
9. User is able to access data using link in email, and download data file.

**Comment by mdmADA** [comment]
Steps.

Access manager accesses the ticket in osticket and deems the access request worthy/unworthy
Access manager clicks the 'Manage permissions' link to go to the dataset
In the dataset, access manager goes to Edit->Permissions->File
In the 'Requests' Section, the access manager finds the user
The access manager clicks Grant (request worthy) or Reject (request unworthy)
Expected results:

Grant/Worthy
a. the user is granted FileDownloader role in the roleassignement table
b. the rows for the user/fileid are deleted from the fileaccessrequests table
c. in the ADA access manager's Dataverse UI, the user moves from the 'Requests' section of the Edit->Permissions->File UI to the ' ' section below to indicate they now have access
d. the requester receives an email saying they have been granted access
e. in the Dataverse ui for the requester, the files' dropdown links that the user has been granted access to now show 'Download'
f. The user can download the file(s)

Reject/Unworthy
a. the rows for the user/fileid are deleted from the fileaccessrequests table
b. in the ADA access manager's Dataverse UI, the user is removed from the 'Requests' section of the Edit->Permissions->File UI
c. the requester receives a notification saying their request has been rejected
d. in the Dataverse UI for the requester, the files' dropdown links once again show 'Request Access' which means the user can request the same files again

MM 14022022: Both Grant and Reject scenarios work
